### ISSUE TITLE
sys-process/bpytop installs everything under /usr/local, not /usr

### ISSUE THREAD

**Issue by fpemud** [wellWINeo/wellWINeo_overlay#1]
localhost ~ # equery files bpytop
 * Searching for bpytop ...
 * Contents of sys-process/bpytop-1.0.1:
/usr
/usr/local
/usr/local/bin
/usr/local/bin/bpytop
/usr/local/share
/usr/local/share/bpytop
/usr/local/share/bpytop/doc
/usr/local/share/bpytop/doc/README.md
/usr/local/share/bpytop/themes
/usr/local/share/bpytop/themes/default_black.theme
/usr/local/share/bpytop/themes/flat-remix-light.theme
/usr/local/share/bpytop/themes/flat-remix.theme
/usr/local/share/bpytop/themes/greyscale.theme
/usr/local/share/bpytop/themes/gruvbox_dark.theme
/usr/local/share/bpytop/themes/index.txt
/usr/local/share/bpytop/themes/monokai.theme
/usr/local/share/bpytop/themes/nord.theme
/usr/local/share/bpytop/themes/solarized_dark.theme
/usr/local/share/bpytop/themes/whiteout.theme

**Comment by wellWINeo** [comment]
Thanks for your attention;)  i fixed it
